### ISSUE TITLE
Jump to and toggle the next keyword on line

### ISSUE THREAD

**Issue by hanschen** [Konfekt/vim-CtrlXA#10]
I'm often in the situation where I have a line like

    some_variable = True

and I want to toggle it to

    some_variable = False

Currently I have to place the cursor somewhere on `True` to toggle it (actually, placing the cursor on `=` or on the space before `=` gives some unexpected behavior).

It would be nice if I could place the cursor anywhere on the line up to and including `True` and hit Ctrl+A to toggle it. This would be consistent with how Vim's Ctrl+A/X work, e.g.

    some_variable = 0

Pressing Ctrl+A anywhere on that line up to and including `0` will put the cursor on `0` and increment it.

**Comment by Konfekt** [comment]
Thank you for pointing this out. That was always how it was meant to work, but somehow did no longer. Should be fixed now.

**Comment by hanschen** [comment]
Thanks for looking into this so quickly. Now it works if my cursor is placed anywhere after `some_variable`, but it still doesn't work for me if the cursor is on `some_variable`. Any tips how I can debug this?

**Comment by Konfekt** [comment]
Please test the latest commit to this end.

**Comment by hanschen** [comment]
Now it works as expected, many thanks again for the speedy solution!

Just a note, there's still some weird behavior when there are multiply keywords on a single line, e.g.

    some_variable = 1, True

or

    some_variable = True, True

I would expect the plugin to change the first keyword under or to the right of the cursor. The current behavior for the first example, with the cursor on the variable name, is that it skips the `1` and toggles `True`. In the second example, I first get `False, True`, then `False, False`, then `True, False`, and afterwards it toggles the first boolean.

Now I don't expect to encounter this situation often enough for it to be an issue, just thought you might want to know. I can open a separate issue for this if you want.

**Comment by Konfekt** [comment]
I get the example with a number and will think about a fix, but the second I cannot reproduce.
Edit: I can.

**Comment by Konfekt** [comment]
Please check the latest commit.

**Comment by hanschen** [comment]
Almost there. Now the examples above work, but I get an error for

    some_variable = 1

with the error message 

```
Error detected while processing function CtrlXA#SingleInc:                                
line   68:
E108: No such variable: "min_i"
```

**Comment by Konfekt** [comment]
Thank you for pointing this out. Please check the latest commit.

**Comment by Konfekt** [comment]
Also in visual mode, in particular `g<c-x/a>` for an ascending/descending enumeration.

**Comment by Konfekt** [comment]
Other points of failure are toggles containing non-keyword characters such as `==` becoming `!=`.

**Comment by hanschen** [comment]
Awesome, thanks. I'm happy with how it currently works. It breaks Vim's default behavior for Ctrl-A/X and numbers because of #8, but I think I'm fine with that. Feel free to close this issue.
